name: knowgo
version: 1.0.3+1
description: KnowGo Platform REST API client
repository: https://github.com/knowgoio/knowgo-client-dart
issue_tracker: https://github.com/knowgoio/knowgo-client-dart/issues
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  http: ^0.12.2
dev_dependencies:
  test: ^1.3.0
